export const COGNITO_AUTHENTICATION = 'COGNITO_AUTHENTICATION'

export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'
export const SIGN_UP_ERROR = 'SIGN_UP_SIGN_UP_ERROR'

export const APPLICATION = 'APPLICATION'
export const APPLICATION_SUCCESS = 'APPLICATION_SUCCESS'
export const APPLICATION_ERROR = 'APPLICATION_ERROR'

export const APPLICATION_EMAIL_VERIFICATION = 'APPLICATION_EMAIL_VERIFICATION'
export const APPLICATION_EMAIL_VERIFICATION_SUCCESS =
  'APPLICATION_EMAIL_VERIFICATION_SUCCESS'
export const APPLICATION_EMAIL_VERIFICATION_FAILURE =
  'APPLICATION_EMAIL_VERIFICATION_FAILURE'
export const APPLICATION_EMAIL_VERIFICATION_ERROR =
  'APPLICATION_EMAIL_VERIFICATION_ERROR'

export const APPLICATION_PHONE_NUMBER_VERIFICATION =
  'APPLICATION_PHONE_NUMBER_VERIFICATION'
export const APPLICATION_PHONE_NUMBER_VERIFICATION_SUCCESS =
  'APPLICATION_PHONE_NUMBER_VERIFICATION_SUCCESS'
export const APPLICATION_PHONE_NUMBER_VERIFICATION_FAILURE =
  'APPLICATION_PHONE_NUMBER_VERIFICATION_FAILURE'
export const APPLICATION_PHONE_NUMBER_VERIFICATION_ERROR =
  'APPLICATION_PHONE_NUMBER_VERIFICATION_ERROR'

export const APPLICATION_COMPLETE = 'APPLICATION_COMPLETE'
export const APPLICATION_COMPLETE_SUCCESS = 'APPLICATION_COMPLETE_SUCCESS'
export const APPLICATION_COMPLETE_ERROR = 'APPLICATION_COMPLETE_ERROR'

export const APPLIED_USER_REGISTRATION = 'APPLIED_USER_REGISTRATION'
export const APPLIED_USER_REGISTRATION_SUCCESS =
  'APPLIED_USER_REGISTRATION_SUCCESS'
export const APPLIED_USER_REGISTRATION_ERROR = 'APPLIED_USER_REGISTRATION_ERROR'

export const NEW_USER_REGISTRATION = 'NEW_USER_REGISTRATION'
export const NEW_USER_REGISTRATION_SUCCESS = 'NEW_USER_REGISTRATION_SUCCESS'
export const NEW_USER_REGISTRATION_ERROR = 'NEW_USER_REGISTRATION_ERROR'

export const REGISTRATION_EMAIL_VERIFICATION = 'REGISTRATION_EMAIL_VERIFICATION'
export const REGISTRATION_EMAIL_VERIFICATION_SUCCESS =
  'REGISTRATION_EMAIL_VERIFICATION_SUCCESS'
export const REGISTRATION_EMAIL_VERIFICATION_FAILURE =
  'REGISTRATION_EMAIL_VERIFICATION_FAILURE'
export const REGISTRATION_EMAIL_VERIFICATION_ERROR =
  'REGISTRATION_EMAIL_VERIFICATION_ERROR'

export const REGISTRATION_PHONE_NUMBER_VERIFICATION =
  'REGISTRATION_PHONE_NUMBER_VERIFICATION'
export const REGISTRATION_PHONE_NUMBER_VERIFICATION_SUCCESS =
  'REGISTRATION_PHONE_NUMBER_VERIFICATION_SUCCESS'
export const REGISTRATION_PHONE_NUMBER_VERIFICATION_FAILURE =
  'REGISTRATION_PHONE_NUMBER_VERIFICATION_FAILURE'
export const REGISTRATION_PHONE_NUMBER_VERIFICATION_ERROR =
  'REGISTRATION_PHONE_NUMBER_VERIFICATION_ERROR'

export const NEW_USER_COGNITO_REGISTRATION = 'NEW_USER_COGNITO_REGISTRATION'
export const NEW_USER_COGNITO_REGISTRATION_SUCCESS =
  'NEW_USER_COGNITO_REGISTRATION_SUCCESS'
export const NEW_USER_COGNITO_REGISTRATION_ERROR =
  'NEW_USER_COGNITO_REGISTRATION_ERROR'

export const NEW_USER_COGNITO_COMPLETE = 'NEW_USER_COGNITO_COMPLETE'
export const NEW_USER_COGNITO_COMPLETE_SUCCESS =
  'NEW_USER_COGNITO_COMPLETE_SUCCESS'
export const NEW_USER_COGNITO_COMPLETE_ERROR = 'NEW_USER_COGNITO_COMPLETE_ERROR'

export const ADMIN_SIGN_IN_SUCCESS = 'ADMIN_SIGN_IN_SUCCESS'
export const ADMIN_SIGN_IN_FAILURE = 'ADMIN_SIGN_IN_FAILURE'
export const ADMIN_SIGN_IN_ERROR = 'ADMIN_SIGN_IN_ERROR'

export const ADMIN_GET_APPLICATIONS_SUCCESS = 'ADMIN_GET_APPLICATIONS_SUCCESS'
export const ADMIN_GET_APPLICATIONS_ERROR = 'ADMIN_GET_APPLICATIONS_ERROR'

export const ADMIN_DELETE_APPLICATION_SUCCESS =
  'ADMIN_DELETE_APPLICATION_SUCCESS'
export const ADMIN_DELETE_APPLICATION_ERROR = 'ADMIN_DELETE_APPLICATION_ERROR'

export const ADMIN_SEND_INVITATION_SUCCESS = 'ADMIN_SEND_INVITATION_SUCCESS'
export const ADMIN_SEND_INVITATION_ERROR = 'ADMIN_SEND_INVITATION_ERROR'

export const ADMIN_GET_INVITATIONS_SUCCESS = 'ADMIN_GET_INVITATIONS_SUCCESS'
export const ADMIN_GET_INVITATIONS_ERROR = 'ADMIN_GET_INVITATIONS_ERROR'

export const ADMIN_GENERATE_INVITATIONS_SUCCESS =
  'ADMIN_GENERATE_INVITATIONS_SUCCESS'
export const ADMIN_GENERATE_INVITATIONS_ERROR =
  'ADMIN_GENERATE_INVITATIONS_ERROR'

export const ADMIN_DELETE_INVITATION_SUCCESS = 'ADMIN_DELETE_INVITATION_SUCCESS'
export const ADMIN_DELETE_INVITATION_ERROR = 'ADMIN_DELETE_INVITATION_ERROR'
